// Componentes UI básicos
// Nota: Estos son componentes simplificados. En un proyecto real,
// instala shadcn-vue para obtener componentes completos:
// npx shadcn-vue@latest init
// npx shadcn-vue@latest add button card input label badge avatar separator switch checkbox select dropdown-menu table sidebar

export { default as Button } from './Button.vue'
export { default as Card } from './Card.vue'
export { default as CardHeader } from './CardHeader.vue'
export { default as CardTitle } from './CardTitle.vue'
export { default as CardDescription } from './CardDescription.vue'
export { default as CardContent } from './CardContent.vue'
export { default as CardFooter } from './CardFooter.vue'
export { default as Input } from './Input.vue'
export { default as Label } from './Label.vue'
export { default as Badge } from './Badge.vue'
export { default as Avatar } from './avatar/Avatar.vue'
export { default as Separator } from './Separator.vue'
export { default as Switch } from './Switch.vue'
export { default as Checkbox } from './Checkbox.vue'
export { default as Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from './Select.vue'
export { default as DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuGroup } from './DropdownMenu.vue'
export { default as Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from './Table.vue'
export { default as Sidebar } from './sidebar/Sidebar.vue'
export { default as SidebarProvider } from './sidebar/SidebarProvider.vue'
export { default as SidebarInset } from './sidebar/SidebarInset.vue'
export { default as SidebarTrigger } from './sidebar/SidebarTrigger.vue'
export { default as SidebarContent } from './sidebar/SidebarContent.vue'
export { default as SidebarHeader } from './sidebar/SidebarHeader.vue'
export { default as SidebarFooter } from './sidebar/SidebarFooter.vue'
export { default as SidebarGroup } from './sidebar/SidebarGroup.vue'
export { default as SidebarGroupLabel } from './sidebar/SidebarGroupLabel.vue'
export { default as SidebarGroupContent } from './sidebar/SidebarGroupContent.vue'
export { default as SidebarMenu } from './sidebar/SidebarMenu.vue'
export { default as SidebarMenuItem } from './sidebar/SidebarMenuItem.vue'
export { default as SidebarMenuButton } from './sidebar/SidebarMenuButton.vue'
export { default as SidebarMenuSub } from './sidebar/SidebarMenuSub.vue'
export { default as SidebarMenuSubItem } from './sidebar/SidebarMenuSubItem.vue'
export { default as SidebarMenuSubButton } from './sidebar/SidebarMenuSubButton.vue'
export { default as SidebarRail } from './sidebar/SidebarRail.vue'
export { default as SidebarSeparator } from './sidebar/SidebarSeparator.vue'
export { useSidebar } from './sidebar/utils.ts'
